version: '3.8'

services:
  pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    image: llmsimt-hakeem:latest
    container_name: llmsimt-hakeem
    ports:
      - "8003:8003"  # host:container
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./models:/app/models
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]