#!/usr/bin/env python3
"""
Hakeem Secret Generator

Generate cryptographically secure secrets for all services.
Supports interactive mode (prompts with defaults) and random mode.

Usage:
  python scripts/generate_secrets.py              # Interactive
  python scripts/generate_secrets.py --random      # Generate all, print summary
  python scripts/generate_secrets.py --random --stdout  # Print as .env format
  python scripts/generate_secrets.py --random --format=yaml  # Print as YAML
"""

import argparse
import os
import secrets
import string
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent


def random_hex(nbytes: int = 32) -> str:
    return secrets.token_hex(nbytes)


def random_password(length: int = 16) -> str:
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def random_urlsafe(length: int = 24) -> str:
    return secrets.token_urlsafe(length)


def prompt(label: str, default: str, secret: bool = True) -> str:
    display = default[:12] + "..." if secret and len(default) > 12 else default
    prompt_str = f"  {label} [{display}]: "
    val = input(prompt_str).strip()
    if not val:
        return default
    return val


def write_env(path: Path, data: dict[str, str], header: str = "") -> None:
    lines = []
    if header:
        lines.append(header)
    for k, v in data.items():
        lines.append(f'{k}={v}')
    lines.append("")
    path.write_text("\n".join(lines))


def write_config_yaml(path: Path, db_password: str, jwt_secret: str) -> None:
    lines = [
        "# Hakeem Backend — Generated Config",
        "# Auto-generated by scripts/generate_secrets.py",
        "# Do NOT commit this file to version control.",
        "",
        "api:",
        '  host: "0.0.0.0"',
        "  port: 8080",
        "  debug: false",
        "  cors_origins:",
        '    - "*"',
        '  rate_limit: "60/minute"',
        "  max_audio_size_mb: 10",
        "  ws_max_size: 10485760",
        "  allowed_audio_types:",
        '    - "audio/wav"',
        '    - "audio/mpeg"',
        '    - "audio/ogg"',
        "",
        "redis:",
        f'  url: "redis://:{db_password}@localhost:6379/0"',
        "  pool_size: 20",
        "  socket_keepalive: true",
        "  socket_connect_timeout: 5",
        "  health_check_interval: 30",
        "",
        "jwt:",
        f'  secret: "{jwt_secret}"',
        '  algorithm: "HS256"',
        "  expiry_minutes: 1440",
        "",
        "cluster:",
        '  node_id: "node-1"',
        '  node_role: "worker"',
        '  pubsub_channel: "hakeem:events"',
        "",
        "auth:",
        "  jwt_only: true",
        "  api_keys: {}",
        "",
        "session:",
        "  ttl_seconds: 86400",
        "  max_history: 100",
        "  heartbeat_interval: 30",
        "  summarize_after: 10",
        "  summarize_keep_last: 5",
        "",
        "tool:",
        "  remote_timeout: 30.0",
        "  internal_timeout: 10.0",
        "  max_retries: 2",
        "",
        "stt:",
        '  model_name: "medium"',
        '  model_dir: "./models"',
        '  hf_repo: "Systran/faster-whisper-medium"',
        '  device: "auto"',
        '  compute_type: "int8"',
        "  beam_size: 5",
        "  vad_filter: true",
        "  language: null",
        "",
        "tts:",
        '  model_dir: "./models"',
        "  voices:",
        "    en:",
        '      local_path: "TTS-CORI-EN"',
        '      hf_repo: "rhasspy/piper-voices"',
        '      voice: "en.en_GB.cori.high"',
        "      use_cuda: false",
        "    ar:",
        '      local_path: "TTS-KAREEM-ARABIC"',
        '      hf_repo: "rhasspy/piper-voices"',
        '      voice: "ar.ar_JO.kareem.medium"',
        "      use_cuda: false",
        '  default_voice: "en"',
        "  max_length: 500",
        "  synthesis:",
        "    volume: 0.75",
        "    length_scale: 1.0",
        "    noise_scale: 0.75",
        "    noise_w_scale: 0.5",
        "    normalize_audio: true",
        "    nchannels: 1",
        "    sampwidth: 2",
        "    framerate: 22050",
        "",
        "llm:",
        '  api_base_url: "https://api.groq.com/openai/v1"',
        '  api_key: "YOUR_LLM_API_KEY"',
        '  model: "llama-3.3-70b-versatile"',
        "  timeout: 60.0",
        "  max_retries: 2",
        '  system_prompt: |',
        "    You are a concise voice assistant.",
        "    Give short, natural spoken answers.",
        '    Avoid bold text, markdown lists, bullet points, or long explanations unless asked.',
        "    Respond in the same language as the user's message.",
        "",
        "mcp:",
        "  servers: []",
        "  sse_read_timeout: 300.0",
        "  tool_timeout: 30.0",
        "  max_retries: 2",
        "  max_tool_loops: 5",
        "",
        "pipeline:",
        '  stt_stream: "stt_jobs"',
        '  llm_stream: "llm_jobs"',
        '  tts_stream: "tts_jobs"',
        '  response_stream: "responses"',
        '  consumer_group: "hakeem_workers"',
        '  consumer_prefix: "worker"',
        "  stt_max_retries: 3",
        "  llm_max_retries: 2",
        "  tts_max_retries: 3",
        "  poll_timeout_ms: 5000",
        "  stt_workers: 1",
        "  llm_workers: 1",
        "  tts_workers: 1",
        "  ws_workers: 1",
        "",
        "medrag:",
        "  enabled: false",
        '  qdrant_host: "localhost"',
        "  qdrant_port: 6333",
        "  domains:",
        '    - "hepatology"',
        '    - "nephrology"',
        '    - "neurology"',
        "  domain_source_dirs: {}",
        '  router_model_path: "./models/medical_router"',
        "  router_threshold: 0.6",
        "  child_chunk_size: 128",
        "  child_chunk_overlap: 16",
        "  parent_chunk_size: 1024",
        "  parent_chunk_overlap: 64",
        "  hybrid_top_k: 30",
        "  reranker_top_k: 5",
        "  rrf_k: 60",
        '  reranker_model_path: "./models/bge_reranker"',
        '  reranker_device: "auto"',
        "  decomposer_enabled: true",
        "  decomposer_num_queries: 3",
        '  neo4j_uri: "bolt://localhost:7687"',
        '  neo4j_user: "neo4j"',
        f'  neo4j_password: "{db_password}"',
        "  graph_traversal_depth: 2",
        "  crag_enabled: true",
        '  llm_model: "unsloth/gemma-4-E2B"',
        "  evaluate_hallucinations: false",
        "  evaluation_max_retries: 1",
        '  model_dir: "./models/chroma"',
        '  device: "auto"',
        "  indexing_batch_size: 16",
        "  indexing_delay_ms: 100",
        "  auto_index_on_start: true",
        "",
        "models:",
        '  storage_path: "./models"',
        "  download_on_startup: true",
        "",
    ]
    path.write_text("\n".join(lines))


def write_infra_compose(path: Path, db_password: str) -> None:
    content = path.read_text()
    old = 'NEO4J_AUTH=neo4j/69397516'
    new = f'NEO4J_AUTH=neo4j/{db_password}'
    if old in content:
        content = content.replace(old, new)
    path.write_text(content)


def generate_interactive() -> None:
    print("\nHakeem Secret Generator".center(50, "="))
    print("  Press Enter to accept the auto-generated default,")
    print("  or type your own value.\n")

    jwt_secret = prompt("JWT Secret", random_hex(32))
    db_password = prompt("DB Password (Redis / Neo4j / Qdrant)", random_password(16))
    llm_api_key = prompt("LLM API Key (leave empty to skip)", "", secret=False)

    print("\n" + "=" * 50)
    print("Generated Secrets Summary")
    print("=" * 50)
    print(f"  JWT_SECRET:     {jwt_secret}")
    print(f"  DB_PASSWORD:    {db_password}")
    print(f"  LLM_API_KEY:    {llm_api_key or '(not set)'}")
    print()

    if input("Write to .env? (y/N): ").strip().lower() == "y":
        env_data = {
            "JWT_SECRET": jwt_secret,
            "DB_PASSWORD": db_password,
            "REDIS_PASSWORD": db_password,
            "NEO4J_PASSWORD": db_password,
        }
        if llm_api_key:
            env_data["LLM_API_KEY"] = llm_api_key
        write_env(
            REPO_ROOT / ".env",
            env_data,
            header="# Hakeem Backend — Generated Secrets\n# Generated by scripts/generate_secrets.py\n# Do NOT commit this file.\n",
        )
        print("  ✓ .env written")

    if input("Write to config.yaml? (y/N): ").strip().lower() == "y":
        write_config_yaml(REPO_ROOT / "config.yaml", db_password, jwt_secret)
        print("  ✓ config.yaml written")

    if input("Update docker-compose.infra.yml? (y/N): ").strip().lower() == "y":
        write_infra_compose(REPO_ROOT / "docker-compose.infra.yml", db_password)
        print("  ✓ docker-compose.infra.yml updated")

    print("\nDone.")

    if not llm_api_key:
        print("\n⚠  Remember to set LLM_API_KEY in .env before running.")


def generate_random(args: argparse.Namespace) -> None:
    jwt_secret = random_hex(32)
    db_password = random_password(16)

    if args.stdout or args.format:
        fmt = args.format or "env"
        if fmt == "env":
            print(f"JWT_SECRET={jwt_secret}")
            print(f"DB_PASSWORD={db_password}")
            print(f"REDIS_PASSWORD={db_password}")
            print(f"NEO4J_PASSWORD={db_password}")
        elif fmt == "yaml":
            print(f'jwt:')
            print(f'  secret: "{jwt_secret}"')
            print(f'redis:')
            print(f'  password: "{db_password}"')
            print(f'  url: "redis://:{db_password}@localhost:6379/0"')
        return

    env_data = {
        "JWT_SECRET": jwt_secret,
        "DB_PASSWORD": db_password,
        "REDIS_PASSWORD": db_password,
        "NEO4J_PASSWORD": db_password,
    }

    write_env(
        REPO_ROOT / ".env",
        env_data,
        header="# Hakeem Backend — Generated Secrets\n# Generated by scripts/generate_secrets.py\n# Do NOT commit this file.\n",
    )
    write_config_yaml(REPO_ROOT / "config.yaml", db_password, jwt_secret)
    write_infra_compose(REPO_ROOT / "docker-compose.infra.yml", db_password)

    print("=" * 50)
    print("Hakeem Secrets Generated")
    print("=" * 50)
    print(f"  JWT_SECRET:     {jwt_secret}")
    print(f"  DB_PASSWORD:    {db_password}    (Redis / Neo4j / Qdrant)")
    print()
    print("  Written to:")
    print("    ✓ .env")
    print("    ✓ config.yaml")
    print("    ✓ docker-compose.infra.yml")
    print()
    print("⚠  LLM_API_KEY was not set — add it to .env manually.")
    print("⚠  config.yaml and .env are now in .gitignore — they won't be committed.")


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate secrets for Hakeem Backend")
    parser.add_argument("--random", action="store_true", help="Generate all secrets non-interactively")
    parser.add_argument("--stdout", action="store_true", help="Print secrets to stdout (implies --random)")
    parser.add_argument("--format", choices=["env", "yaml"], default=None, help="Output format for --stdout")
    args = parser.parse_args()

    if args.stdout:
        args.random = True
        args.format = args.format or "env"

    if args.random:
        generate_random(args)
    else:
        generate_interactive()


if __name__ == "__main__":
    main()
